### ISSUE TITLE
Error: cannot estimate gas; transaction may fail or may require manual gas limit 

### ISSUE THREAD

**Issue by pranavkirtani** [aave/aave-utilities#343]
# Bug Report

## Description
Error: cannot estimate gas; transaction may fail or may require manual gas limit 

## Steps to reproduce
After calling supply as mentioned in readme and after erc20 approval, when i try to trigger supply by calling ts.tx(), i get gas estimation error

## Environment

- OS: [e.g., OSX 10.13.4, Windows 10]
- Node/npm version: [e.g., Node 8/npm 5]
- Browser: [e.g., Chrome]

**Comment by iluvboba** [comment]
same thing is happening for me

**Comment by olvresc** [comment]
Hi @pranavkirtani, could you provide a code snippet? I was able to push a transaction using v3 without error;

**Comment by About7Sharks** [comment]
similar, approval goes through but supply errors. Testing on mumbai.

**Comment by About7Sharks** [comment]
After more poking around it also appears these [docs](https://docs.aave.com/developers/guides/testing-guide#test-markets) which references using the app for test networks is also failing at estimating the gas. I also made sure to toggle into aave's testnet mode.
![image](https://user-images.githubusercontent.com/30053857/174683969-7f9abe00-c194-4646-890f-b44f4ac7165f.png)

**Comment by iamsiddhant05** [comment]
I'm facing the same problem when executing the `tx` from borrow method, but i was able to run supply method.

Plus seems like the snippet in readme is wrong for borrow(v3)

**Comment by defispartan** [comment]
Gas estimation error is a generic error for a failing transactions. Most common issues can be:

- Invalid asset address
- Insufficient balance

If you have a failed txHash we can debug the exact error.
