### ISSUE TITLE
the getUserWalletBalancesForLendingPoolProvider method in WalletBalanceProvider, does not validate the user address correctly.

### ISSUE THREAD

**Issue by dMarin178** [aave/aave-utilities#388]
# Bug Report

## Package name / version
aave-utilities / v 1.4.0

## Description
When am trying to use the method getUserWalletBalanceForLendingPoolProvider for a wallet in rinkeby testnet
the method throws me an error that the address is not valid. I checked the address with ethers.utils method and returns true. 
I check the steps to fetch the data in the documentation and it should work.

Most likely i made a mistake in some step, but here is what i did.

## Steps to reproduce
install
// with npm
```
npm install --save-dev ethers reflect-metadata
npm install @aave/contract-helpers @aave/math-utils
```

create a project in Infura for rinkeby testnet chain
[](https://infura.io)

script:
```
import { ethers } from "ethers";
import pkg from "@aave/contract-helpers";
import math_pkg from "@aave/math-utils";
import dotenv from "dotenv";
dotenv.config({ silent: process.env.NODE_ENV === "production" });
const { UiPoolDataProvider, UiIncentiveDataProvider, ChainId, WalletBalanceProvider } = pkg;
const { formatReserves, formatReservesAndIncentives, formatUserSummary, formatUserSummaryAndIncentives } =
  math_pkg;


//Provider
provider = new ethers.providers.StaticJsonRpcProvider(
  "https://rinkeby.infura.io/v3/process.env.INFURA_KEY",
  ChainId.rinkeby
);

const walletBalanceProviderAddress = "0x116674C3Efe4e31F192d855284619DEd6fE2a1b9";
const lendingPoolAddressProvider = "0xBA6378f1c1D046e9EB0F538560BA7558546edF3C";

//User address
const user = process.env.USER_ADDRESS;

//Check if address is valid
console.log(ethers.utils.isAddress(user));

async function main(){
  const walletBalanceProvider = new WalletBalanceProvider({
    walletBalanceProviderAddress,
    provider,
  });

  //console.log(walletBalanceProvider)

  const walletUserBalance = await walletBalanceProvider.getUserWalletBalancesForLendingPoolProvider({
    user,
    lendingPoolAddressProvider,
  });

  //console.log(walletUserBalance);
}

main();

```

## Expected behavior

according to the doc. in index. should return 
  /**
   *  Provides balances of user wallet for all reserves available on the pool
   * /

## Environment

- OS: [e.g., Ubuntu 20.04.4, Linux]
- Node v18.6.0 / npm 8.13.2

## Additional context / screenshots

WalletBalanceProvider

![image](https://user-images.githubusercontent.com/45694366/179344526-3f31f398-e5ad-4646-9b2d-68d315c79f1f.png)

Result

![image](https://user-images.githubusercontent.com/45694366/179345177-f7a2f293-1db6-49ac-ab89-d25cf222753a.png)

**Comment by defispartan** [comment]
This line:

```
  const walletUserBalance = await walletBalanceProvider.getUserWalletBalancesForLendingPoolProvider({
    user,
    lendingPoolAddressProvider,
  });
```

Should be

```
  const walletUserBalance = await walletBalanceProvider.getUserWalletBalancesForLendingPoolProvider(
    user,
    lendingPoolAddressProvider,
  );
```
