### ISSUE TITLE
UiPoolDataProvider.getReservesHumanized not working

### ISSUE THREAD

**Issue by olivbau** [aave/aave-utilities#431]
# Bug Report

## Package name / version
@aave/contract-helpers v1.7.1

## Description
UiPoolDataProvider.getReservesHumanized() throw an error.

Error:
`eModeLabel: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber", value="312070026614174355834089907303725153299629842722816", code=NUMERIC_FAULT, version=bignumber/5.7.0)`

ChainId used: `ChainId.avalanche`
Providers used:
        
        lendingPoolAddressProvider: '0xa97684ead0e402dc232d5a977953df7ecbab3cdb'
        uiIncentiveDataProviderAddress: '0x270f51cf3f681010b46f5c4ee2ad5120db33026f'
        uiPoolDataProviderAddress: '0xdbbfafc45983b4659e368a3025b81f69ab6e5093'

**Comment by khelil** [comment]
Hi @olivbau 🖖 can you please share the right address for those provider...i have the same error and can't find them

**Comment by khelil** [comment]
Nevermind...got them :

const uiPoolDataProviderAddress = "0xa7da242e099136A71fF975B8D78b79AA543c9182";
const uiIncentiveDataProviderAddress = "0x11979886A6dBAE27D7a72c49fCF3F23240D647bF";
const lendingPoolAddressProvider = "0xb6A86025F0FE1862B372cb0ca18CE3EDe02A318f";
